#!/bin/bash

# NUMBER OF WORKERS
NUM_WORKERS=8

# ROOT INPUT AND OUTPUT FOLDERS
INPUT_ROOT_FOLDER=/mnt/store/data/covid/data/Large_Study/COVID_19_POCT
OUTPUT_ROOT_FOLDER=/mnt/store/data/covid/results/Large_Study/COVID_19_POCT/

#
# Camera 1
#
CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera1/100CANON/sorted/
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera1

MANUFACTURER=AUGURIX
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera1.conf -w ${NUM_WORKERS}

MANUFACTURER=CTKBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera1.conf -w ${NUM_WORKERS}

MANUFACTURER=SUREBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera1.conf -w ${NUM_WORKERS}

MANUFACTURER=BIOZAK
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera1.conf -w ${NUM_WORKERS}

#
# Camera 2

CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera2/100EOS5D/sorted/
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera2

# # # NOTE # # # THIS DOES NOT WORK AT ALL! # # #
MANUFACTURER=SUREBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera2.conf -w ${NUM_WORKERS}


#
# Camera 3
#
CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera3/100CANON/sorted/
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera3

MANUFACTURER=CTKBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera3.conf -w ${NUM_WORKERS}

MANUFACTURER=SUREBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera3.conf -w ${NUM_WORKERS}

MANUFACTURER=BIOZAK
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera3.conf -w ${NUM_WORKERS}

#
# Camera 4
#
CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera4/102MSDCF/sorted
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera4

MANUFACTURER=CTKBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera4.conf -w ${NUM_WORKERS}

MANUFACTURER=SUREBIOTECH
# python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera4.conf -w ${NUM_WORKERS}

# # # NOTE # # # THIS DOES NOT WORK AT ALL! # # #
MANUFACTURER=BIOZAK
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera4.conf -w ${NUM_WORKERS}

#
# Camera 6
#

CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera6/sorted
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera6

MANUFACTURER=CTKBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera6.conf -w ${NUM_WORKERS}

MANUFACTURER=SUREBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera6.conf -w ${NUM_WORKERS}

MANUFACTURER=BIOZAK
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera6.conf -w ${NUM_WORKERS}

#
# Camera 9
#

CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera9/sorted
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera9

MANUFACTURER=CTKBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera9.conf -w ${NUM_WORKERS}

MANUFACTURER=SUREBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera9.conf -w ${NUM_WORKERS}

MANUFACTURER=BIOZAK
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera9.conf -w ${NUM_WORKERS}

#
# Camera 11
#

CAMERA_INPUT_FOLDER=${INPUT_ROOT_FOLDER}/Camera11/DCIM/100EOS5D/sorted
CAMERA_OUTPUT_FOLDER=${OUTPUT_ROOT_FOLDER}/Camera11

# # # NOTE # # # THIS DOES NOT WORK AT ALL! # # #

MANUFACTURER=SUREBIOTECH
#python pyPOCQuant.py -f ${CAMERA_INPUT_FOLDER}/${MANUFACTURER}/ -o ${CAMERA_OUTPUT_FOLDER}/${MANUFACTURER}/ -s ./config/config_FH_${MANUFACTURER}_camera11.conf -w ${NUM_WORKERS}
